language: node_js

branches:
  only:
    - master

before_script: bash ./bin/build.sh

script:
    - ls -al js/gsimaps.min.js

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/miya0001/sandmaps.github.io.git
  - secure: "o/cCKTYmJNLiRE1134pQ4bpXkQT3dKj582IMBxN/AMX3QmI8bP8Sd0+KTwl3EV5bjJMD6w/IB//3rx1sXSshHgaCSPBdhINWPraQppBetFKGWOv6v2LSmGZxjJxjymY7Ib9Il0vNDAZXhq5evpPTXou73HRnwELyw0QGnPUEjf2pJaKjHWuVu1SzZquHAl7vc/VCA2R0DCR82ZEVHooX2GpiH6Xu6WlS5+lrWprHvXO3oLbbSsb/vqf1utgmx96ggs/vHuyYaUll3h0kQ3HY0nM+pEwOGXt1XQDQFfjNCnnWyzSYfGqKxtoWEXxExGV8ymnpY+8KSk6AxBlbv13iadhqPS48hKqf1fpz6LpTEW2CZq5STRHo+l/7by5FlgbhRVUimepkjyVGrspluP/WbE7ttZwFUDpF8gr2JhO9bgNbfcZUaj5MrRHuCyv2nFsaOBXn3zP/t2xfDwh3bfyE+RIf9z6GUvqSYNL0BpCpqH2FzlHvOyQClG7SuX8Do5rL2lw0xtB71AiSQg5UU1BDKLiyzxClJ1PjpBOHgJtp5sK92CesKFTVJjXrYDDLTQqrBJHySQwTKLiQq/0o8Tor4VWk0Oz96SZ5AwcGtwo1zQ4MphxGMxSSimqV9eS/8ISvhrRl4iXC+PMmNTBLkpHhAlULHC7q/M+KLtj0ZsderpU="
