language: node_js

branches:
  only:
    - master

before_script: bash ./bin/build.sh

script:
    - ls -al js/gsimaps.min.js

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/sandmaps/sandmaps.github.io.git
  - secure: "Swv2v4x0xmOPMK8TdiggDR+u/8CjNEFIh5ArBDdibHU/iAIuMeY+QM60cVhmPfqPqvyc2pmQ83bt6BvRUrvSe/cNsOOGDxBN8EKdECk276zFuUSSEeqjPXv28uoKggcZ+IgGC4dCzC6OwaIzz05V9oEdd71+Q4mNSyAuAUK12TLtVQjvtKbfd9Js9Vsoqfe/jA9qM7OZCXnDPs12bm/RM0Cv287TO5cNoFBn3S1365g3K0N3CLnaFqoOtJPLYH24ZkAFCXxcQOTxtgzJXYJZJqWmg85ZIz+EoPKKbra5bya1un/aIVnkIiySeCXkMHOubcxYvkwpFzNxrFu6ghvgzee7UaGKCkYYKz42ncIrQYi+eZtlA5xQblv591E6gyWVn7RDRzjlx/jxEWrFb3mUoryXxoUJaPZVQlo1jJxBKMoscTQzyB9bVzdnE440xW3c7YdFShtFPTDTTEU/q4m8fcOvWsKPk8fH3n9yaEuoc53B/ykdtbb6Kw0Rj9MH9FtntkVY1VTeUEOXqv2ThYd4PQmTk/gEN6nBtjHDOtLrKUiMLkUc7rPi+8comTXGnLld1z/X6I+ZcKF0QwDgl2vJjpB9Kq2vTU2NbGozadTFn8eiPkJPcCXI3rjpBwg2qmPaS+ngSRA9vp5tS3ICF7kwYndYZDwrr47PXU0ByqZ279A="
